// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/FeedOperation.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "QZJStyleFeedInfo.h"

@interface QZJStyleApplyUploadReq : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(feed_info,setFeed_info:)) QZJStyleFeedInfo* JV2_PROP_NM(r,0,feed_info);

@end
