// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/FeedOperation.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface QZJStyleApplyUploadRsp : JceObjectV2

@property (nonatomic, retain, JV2_PROP_GS_V2(signature,setSignature:)) NSString* JV2_PROP_NM(r,0,signature);
@property (nonatomic, assign, JV2_PROP_GS_V2(begin_time,setBegin_time:)) JceInt64 JV2_PROP_NM(r,1,begin_time);
@property (nonatomic, assign, JV2_PROP_GS_V2(end_time,setEnd_time:)) JceInt64 JV2_PROP_NM(r,2,end_time);

@end
