// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/FeedOperation.jce'
// **********************************************************************

#import "JceObjectV2.h"

@interface QZJStyleEditParameter : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(place_holder,setPlace_holder:)) JceInt32 JV2_PROP_NM(r,0,place_holder);

@end
