// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/FeedOperation.jce'
// **********************************************************************

#import "QZJStyleFeedInfo.h"

@implementation QZJStyleFeedInfo

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(author_id) = DefaultJceString;
        JV2_PROP(tags) = DefaultJceArray;
        JV2_PROP(stickers) = DefaultJceArray;
        JV2_PROP(parameters) = [QZJStyleEditParameter object];
        JV2_PROP(description) = DefaultJceString;
        JV2_PROP(file_id) = DefaultJceString;
        JV2_PROP(object_ids) = DefaultJceArray;
        JV2_PROP(cover_id) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Style.FeedInfo";
}

@end
