// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/FeedOperation.jce'
// **********************************************************************

#import "JceObjectV2.h"
#import "QZJStyleEditParameter.h"

@interface QZJStyleFeedInfo : JceObjectV2

@property (nonatomic, assign, JV2_PROP_GS_V2(type,setType:)) JceInt32 JV2_PROP_NM(r,0,type);
@property (nonatomic, assign, JV2_PROP_GS_V2(pubish_time,setPubish_time:)) JceInt64 JV2_PROP_NM(r,1,pubish_time);
@property (nonatomic, retain, JV2_PROP_GS_V2(author_id,setAuthor_id:)) NSString* JV2_PROP_NM(r,2,author_id);
@property (nonatomic, assign, JV2_PROP_GS_V2(style,setStyle:)) JceInt32 JV2_PROP_NM(r,3,style);
@property (nonatomic, retain, JV2_PROP_GS_V2(tags,setTags:)) NSArray* JV2_PROP_EX(r,4,tags,VONSNumber);
@property (nonatomic, retain, JV2_PROP_GS_V2(stickers,setStickers:)) NSArray* JV2_PROP_EX(r,6,stickers,VONSNumber);
@property (nonatomic, retain, JV2_PROP_GS_V2(parameters,setParameters:)) QZJStyleEditParameter* JV2_PROP_NM(r,7,parameters);
@property (nonatomic, retain, JV2_PROP_GS_V2(description,setDescription:)) NSString* JV2_PROP_NM(r,8,description);
@property (nonatomic, retain, JV2_PROP_GS_V2(file_id,setFile_id:)) NSString* JV2_PROP_NM(r,9,file_id);
@property (nonatomic, retain, JV2_PROP_GS_V2(object_ids,setObject_ids:)) NSArray* JV2_PROP_EX(r,10,object_ids,VONSString);
@property (nonatomic, retain, JV2_PROP_GS_V2(cover_id,setCover_id:)) NSString* JV2_PROP_NM(r,11,cover_id);

@end
