// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.0.0 by WSRD Tencent.
// Generated from `/Users/a1/newApp/FeedOperation.jce'
// **********************************************************************

#import "QZJStyleApplyUploadRsp.h"

@implementation QZJStyleApplyUploadRsp

- (id)init
{
    if (self = [super init]) {
        JV2_PROP(signature) = DefaultJceString;
    }
    return self;
}

+ (NSString*)jceType
{
    return @"Style.ApplyUploadRsp";
}

@end
